
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: deen
      POSTGRES_PASSWORD: usman
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
